### ISSUE TITLE
I suggest change link type name from "gh:" to "github:"

### ISSUE THREAD

**Issue by stardiviner** [stefanv/org-link-github#1]
In many link type names, the shorten link name "gh:" is meanless, I suggest to use "github:". The "github:" is not long, no need to shorten it.
WDYT?

**Comment by stefanv** [comment]
Thank you for your suggestion @stardiviner!

I type these links very often, so I prefer `gh`. But all you'd need to do to get `github` is to set:

```
(org-link-set-parameters "github"
                         :follow #'org-link-github-open
                         :export #'org-link-github-export)
```
